channels:
- conda-forge
dependencies:
- python=3.13.3
- pip<=25.1.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - matplotlib==3.10.3
  - numpy==2.3.1
  - pandas==2.3.1
  - pytorch-lightning==2.5.2
  - scipy==1.16.0
  - torch==2.7.1
name: mlflow-env
